### PR TITLE
adding idTight 

### PR DESCRIPTION
**Pull request by antoniovagnerini**

### CODE REVIEW

**Comment by robervalwalsh** [comment]
In the ntuple there is no tight id variable. Please check if the variables needed to construct the tight id [1] are already available in the ntuple. If not they needed to be added to the ntuplizer as well as the tight id from the pat::Muon.
[1] https://twiki.cern.ch/twiki/bin/view/CMS/SWGuideMuonIdRun2#Tight_Muon

**Comment by robervalwalsh** [comment]
@antoniovagnerini Did you test these modifications in ntuples that do not contain the tight id variable? If so, I will merge while you implement in the ntuplizer.

**Comment by antoniovagnerini** [comment]
I just checked it compiles. I will make a quick test that it runs without problems on the ntuples, but since the tight id var is absent I do not expect any issue. I will let you know when I am done with the ntuplizer modifications because there a few more variables that have to be added for id tight and that i need to test.

**Comment by antoniovagnerini** [comment]
I ran a test job and it worked fine. I just get this expected error because the ntuples do not contain the idTight yet.
Error in <TChain::SetBranchAddress>: unknown branch -> isTightMuon

I think you can go ahead and merge.

**Comment by robervalwalsh** [comment]
You can do something similar to what is done in [1] below to avoid such messages when using old ntuples. I have been doing that whenever a new variable is added.

[1] https://github.com/desy-cms/analysis-tools/blob/develop/src/PhysicsObjectTree.cc#L112

**Comment by robervalwalsh** [comment]
@antoniovagnerini I will merge this one and wait for another PR with such modification.

**Comment by antoniovagnerini** [comment]
Hi Roberval, 

I noticed that the definition at [1] bool muon::isTightMuon( const [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/df/de3/classreco_1_1Muon.html | reco::Muon ] &, const [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/da/d95/classreco_1_1Vertex.html | reco::Vertex ] & ) requires an input vertex as an argument and this is not implemented in src/Candidates.cc but only in Vertices.cc. 

The vertex position info is used in the impact parameter transverse and longitudinal cuts for the tight id: 

bool ip = fabs(muon. [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/df/de3/classreco_1_1Muon.html#aa09bd58589f06056996ac503ee83565e | innerTrack ] ()->dxy(vtx. [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/da/d95/classreco_1_1Vertex.html#a569b3c1751f63f3f58f42ebb6576324b | position ] ())) < 0.3 && fabs(muon. [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/df/de3/classreco_1_1Muon.html#aa09bd58589f06056996ac503ee83565e | innerTrack ] ()->dz(vtx. [ http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/da/d95/classreco_1_1Vertex.html#a569b3c1751f63f3f58f42ebb6576324b | position ] ())) < 20. 

Tomorrow we can discuss how to integrate the vertex info in candidates. 

Cheers, 

Antonio 

[1] http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_9_2_14_patch2/doc/html/da/d18/namespacemuon.html#a8b4fc4537e8924bf4b544afb2408636d

**Comment by robervalwalsh** [comment]
@antoniovagnerini you probably don’t need the vertex collection explicitly. The muon is reconstructed using a vertex that should have been stored. You should be able to get the vertex information from the pat::Muon inherited class LeafCandidate. For tight muon id it is only the vertex point that is needed. So you can reconstruct a reco::Vertex with only that info. Please check if the error is not used, but you can get the vertex covariance matrix from LeafCandidate too if you want to construct the reco::Vertex.

**Pull request merged**
